export const ACTION_TYPE_SET_FILTER = 'SET_VISIBILITY_FILTER';
export const ACTION_TYPE_ADD_TODO = 'ADD_TODO';
export const ACTION_TYPE_TOGGLE_TODO = 'TOGGLE_TODO';
export const ACTION_TYPE_FILTER = {
    SHOW_ALL: 'VISIBILITY_FILTER_SHOW_ALL',
    SHOW_FINISHED: 'VISIBILITY_FILTER_SHOW_FINISHED',
    SHOW_UNFINISHED: 'VISIBILITY_FILTER_SHOW_UNFINISHED'
};
// export const ACTION_TYPE_FILTER_SHOW_ALL = 'VISIBILITY_FILTER_SHOW_ALL';
// export const ACTION_TYPE_FILTER_SHOW_FINISHED = 'VISIBILITY_FILTER_SHOW_FINISHED';
// export const ACTION_TYPE_FILTER_SHOW_UNFINISHED = 'VISIBILITY_FILTER_SHOW_UNFINISHED';